[package]
name = "imx"
version = "0.1.1"
edition = "2024"
description = "A library for image processing and manipulation"
license = "MIT"

[dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"] }
image = { version = "0.25.5", features = ["png"] }
log = "0.4.25"
tokio = { version = "1.43.0", features = ["full"] }
jxl-oxide = "0.11.2"

[dev-dependencies]
tempfile = "3.17.1"
